package com.example.suhas.indapurmart.common;

/**
 * Created by bhoskar1 on 17/8/17.
 */

public interface ICommonConstants {
    String KEY_CATEGORY_TYPE = "CATEGORY_TYPE";
    String KEY_PARCELABLE_SUB_CATEGORY = "PARCELABLE_SUB_CATEGORY";
    String KEY_PARCELABLE_CATEGORY_ID = "PARCELABLE_CATEGORY_ID";
    String KEY_PARCELABLE_SUB_CATEGORY_ID = "PARCELABLE_SUB_CATEGORY_ID";
    String KEY_PARCELABLE_VILLAGE_ID = "PARCELABLE_VILLAGE_ID";
    String KEY_PARCELABLE_USER = "PARCELABLE_USER";
    String KEY_SHARED_PREFERENCES = "INDAPUR_MART_PREFERENCES";
    String KEY_PREFERENCES_VILLAGE_LIST = "VILLAGE_LIST_PREFERENCE";

    int CATEGORY_MAIN = 1;
    int CATEGORY_SUB = 2;
    int CATEGORY_SUB_SUB = 3;
}
